# Site settings
title: iDPS InfoSec
email: dps.ignacio@protonmail.com
description: Offensive security, penetration testing, and red team experiments.
url: "https://iDPS-infoSec.github.io"

# Social links
github_username: iDPS-infoSec
linkedin_url: https://www.linkedin.com/in/ignaciodps/

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed