# Site settings
title: iDPS InfoSec
email: dps.ignacio@protonmail.com
description: Offensive security, penetration testing, and red team experiments.
baseurl: "" # leave empty for user/organization site
url: "https://iDPS-infoSec.github.io"

# Social links
github_username: iDPS-infoSec
linkedin_url: https://www.linkedin.com/in/ignaciodps/

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
